baseURL = 'https://jasoncpit.github.io/GPU-Analytics/'
languageCode = 'en-us'
title = 'GPU-based analysis for social and geographic applications'
theme = 'hugo-book'
publishDir = "docs"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[markup.tableOfContents]
  startLevel = 1

[menu]
[[menu.after]]
  name = ":mortar_board: Github"
  url = "https://github.com/jtvandijk/GPU-Analytics"
  weight = 10 

[params]

  bookTheme = "auto"
  BookToC = true
  BookSearch = false
  BookTranslatedOnly = false 
  BookDateFormat = 'March 16, 2023'
  BookRepo = 'https://github.com/jtvandijk/GPU-Analytics'
